blank_issues_enabled: true

issue_template:
  - title: "Bug Report"
    body: |
      ## Description
      
      ## Steps to Reproduce
      
      ## Expected Behavior
      
      ## Actual Behavior

  - title: "Feature Request"
    body: |
      ## Summary
      
      ## Motivation
      
      ## Suggested Implementation

  - title: "Question"
    body: |
      ## Question:
      
      ## Additional Information: